- name: Nginx stop
  service:
    name: nginx
    state: stopped

- name: config file copy
  copy: src=/tmp/index.html dest=/var/www/html/index.html owner=root group=root mode=0644

- name: Nginx start
  service:
    name: nginx
    state: started
